import { PickType } from '@nestjs/swagger';
import { Product } from '../entities/product.entity';

export class CreateProductDto extends PickType(Product, [
  'code',
  'buyFormShop',
  'catalog',
  'refOldStockNumber',
  'payPerMonth',
  'valueMonth',
  'imei',
  'fileProduct',
  'batteryHealth',
  'shopInsurance',
  'shopCenterInsurance',
  'hand',
  'simType',
  'randomCode',
  'boxType',
  'freeGift',
  'machineCondition',
  'priceETC',
  'priceCostBuy',
  'priceWholeSale',
  'priceSale',
  'priceReRider',
  'priceRegAppleId',
  'priceRepair',
  'priceDownPayment',
  'priceDownPaymentPercent',
  'priceRepair',
  'priceCommission',
  'productTypeId',
  'venderId',
  'productColorId',
  'productStorageId',
  'productBrandId',
  'productModelId',
  'branchId',
  'createByUserId',
  'amount',
  'active',
] as const) {}
